name: issue comment
on:
  issue_comment:
    types: [created]
jobs:
  issue-comment:
    runs-on: ubuntu-latest
    if : github.event.issue.pull_request != null
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: make log
        run: echo 'make test'
        env:
