name: issue comment
on:
  issue_comment:
    types: [created]
jobs:
  issue-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: make log
        run: |
          echo A comment on PR "$NUMBER"
        env:
          NUMBER: ${{ github.event.issue.number }}
