name: issue comment
on:
  issue_comment:
    types: [created]

jobs:
  issue-comment:
    if: github.event.issue.pull_request && contains(github.event.pull_request.labels.*.name, 'test') && startsWith(github.event.comment.body, '/test update')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo comment on PR "$NUMBER"
        env:
          NUMBER: ${{ github.event.issue.number }}
