name: issue comment
on:
  issue_comment:
    types: [created]
jobs:
  issue-comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo input text "$TEXT", comment on PR "$NUMBER"
        env:
          NUMBER: ${{ github.event.issue.number }}
          TEXT: ${{ github.event.comment.body }}
