name: issue comment
on:
  issue_comment:
    types: [created]

jobs:
  issue-comment:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.*.labels.*.name, 'test') &&
      startsWith(github.event.comment.body, 'test update')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      BASE_URL: dev.example.com
      REPOSITORY_NAME: ${{github.event.repository.name}}
      PR_NUMBER: ${{ github.event.issue.number }}
    steps:
      - run: |
          echo pr-number "$PR_NUMBER"
      - name: add comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            :white_check_mark: test updated https://${{ env.REPOSITORY_NAME }}-${{ env.PR_NUMBER }}.${{ env.BASE_URL }}
