name: issue comment
on:
  issue_comment:
    types: [created]

jobs:
  issue-comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'test update')
    # contains(github.event.pull_request.labels.*.name, 'test') &&
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.pull_request.labels.*.name }}"
      - run: |
          echo "${{ contains(github.event.pull_request.labels.*.name, 'test') }}"
      - run: |
          echo pr-number "$NUMBER"
        env:
          NUMBER: ${{ github.event.issue.number }}
