name: issue comment
on:
  issue_comment:
    types: [created]

jobs:
  issue-comment:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'test update')
    # contains(github.event.pull_request.labels.*.name, 'test') &&
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo val: "$VAL", ret: "$RET" , pr-number: "$NUMBER"
        env:
          VAL: ${{github.event.pull_request.labels.*.name}}
          RET: ${{contains(github.event.pull_request.labels.*.name, 'test')}}
          NUMBER: ${{ github.event.issue.number }}
